# Generated by Django 4.2.13 on 2026-04-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_branchtarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("walkin", "Walk-in")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("record_id", models.PositiveIntegerField(db_index=True)),
                ("follow_up_date", models.DateField()),
                ("next_follow_up_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follow_ups",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["record_type", "record_id"],
                        name="follow_ups_record__76c7a8_idx",
                    )
                ],
            },
        ),
    ]
