# Generated by Django 4.2.13 on 2026-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_followup"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lead",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekday_morning", "Weekdays (Morning)"),
                    ("weekday_evening", "Weekdays (Evening)"),
                    ("weekends", "Weekends"),
                ],
                max_length=30,
            ),
        ),
    ]
