# Generated by Django 4.2.9 on 2026-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0033_enrollment_pending_finalization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="preferred_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekday_morning", "Weekdays (Morning)"),
                    ("weekday_evening", "Weekdays (Evening)"),
                    ("weekends", "Weekends"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("justdial", "JustDial"),
                    ("direct", "Direct"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("friends_reference", "Friends Reference"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("whatsapp", "Whatsapp"),
                    ("justdial", "JustDial"),
                    ("team_reference", "Team Reference"),
                    ("friends_reference", "Friends Reference"),
                    ("others", "Others"),
                ],
                default="google",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("super_admin", "Admin"), ("staff", "Staff")],
                default="staff",
                max_length=20,
            ),
        ),
    ]
