# Generated by Django 4.2.13 on 2026-05-12 10:21

from django.db import migrations, models


def backfill_payment_documents(apps, schema_editor):
    PaymentInstallment = apps.get_model("crm", "PaymentInstallment")
    PaymentInstallment.objects.filter(bill_number__gt="").update(document_type="bill")
    for installment in PaymentInstallment.objects.filter(installment_label="").only("id", "installment_index"):
        installment.installment_label = f"{installment.installment_index} Installment"
        installment.save(update_fields=["installment_label"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("crm", "0046_lead_imported_via_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinstallment",
            name="document_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("bill", "Bill")],
                db_index=True,
                default="receipt",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="installment_index",
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="installment_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="receipt_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.RunPython(backfill_payment_documents, migrations.RunPython.noop),
    ]
