# Generated by Django 4.2.13 on 2026-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0047_paymentinstallment_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("interested", "Interested"),
                    ("will_walk_in", "Will Walk-in"),
                    ("not_interested", "Not Interested"),
                    (
                        "continuously_not_answering_calls",
                        "Continuously Not Answering Calls",
                    ),
                    ("not_answering", "Not Answering"),
                    ("contacted", "Contacted"),
                    ("follow_up", "Follow Up"),
                    ("walk_in", "Walk-in Scheduled"),
                    ("enrolled", "Enrolled"),
                    ("dropped", "Dropped"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="new",
                max_length=40,
            ),
        ),
    ]
