# Generated by Django 4.2.13 on 2026-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0048_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalanalyticsentry",
            name="value_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
