# Generated by Django 4.2.13 on 2026-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0049_historicalanalyticsentry_value_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("counseling_completed", "Counseling Completed"),
                    ("demo_attended", "Demo Attended"),
                    ("interested", "Interested"),
                    ("will_enroll", "Will Enroll"),
                    ("will_walk_in", "Will Walk-in"),
                    ("not_answering", "Not Answering"),
                    ("call_not_attended", "Call Not Attended"),
                    ("switched_off", "Switched Off"),
                    ("wrong_number", "Wrong Number"),
                    ("not_interested", "Not Interested"),
                    ("joined_other_institute", "Joined Other Institute"),
                    ("callback_later", "Callback Later"),
                    ("future_lead", "Future Lead"),
                    (
                        "continuously_not_answering_calls",
                        "Continuously Not Answering Calls",
                    ),
                    ("contacted", "Contacted"),
                    ("follow_up", "Follow Up"),
                    ("walk_in", "Walk-in Scheduled"),
                    ("enrolled", "Enrolled"),
                    ("dropped", "Dropped"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="new",
                max_length=40,
            ),
        ),
    ]
