# Generated by Django 4.2.13 on 2026-05-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0070_counselorchangerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimporthistory",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("leads", "Leads"),
                    ("walkins", "Walk-ins"),
                    ("courses", "Courses"),
                    ("enrollments", "Enrollments"),
                    ("students", "Students"),
                    ("payments", "Payments"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
