# Generated by Django 4.2.13 on 2026-06-08 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_legacy_pending_requests_to_admin_queue(apps, schema_editor):
    WalkInAssignmentChangeRequest = apps.get_model("crm", "WalkInAssignmentChangeRequest")
    WalkInAssignmentChangeRequest.objects.filter(status="pending").update(status="pending_admin_approval")


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0084_walkin_assignment_change_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkinassignmentchangerequest",
            name="counselor_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="walkinassignmentchangerequest",
            name="counselor_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="walkinassignmentchangerequest",
            name="counselor_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="walkin_assignment_counselor_reviewed_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="walkinassignmentchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_counselor_approval", "Pending Counselor Approval"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_counselor_approval",
                max_length=40,
            ),
        ),
        migrations.RunPython(move_legacy_pending_requests_to_admin_queue, migrations.RunPython.noop),
    ]
