# Generated by Django 4.2.13 on 2026-06-18 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0089_adminreceipt_reference_number_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminreceipt",
            name="reference_number",
        ),
    ]
