# Generated by Django 4.2.13 on 2026-09-09 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0102_rules_regulations_document_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="reversal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="reversed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="payment_proof",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="payment_proofs/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_rules_form", "Pending Rules Form"),
                    ("rules_form_sent", "Rules Form Sent"),
                    ("rules_form_submitted", "Rules Form Submitted"),
                    ("enrolled", "Enrolled"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("inactive", "Inactive"),
                    ("dropped", "Dropped"),
                    ("on_hold", "Hold"),
                    ("transferred", "Transferred"),
                    ("reversed_to_walkin", "Reversed to Walk-in"),
                ],
                db_index=True,
                default="pending_rules_form",
                max_length=30,
            ),
        ),
    ]
