# Generated by Django 4.2.13 on 2026-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0103_enrollment_reversal_reason_enrollment_reversed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="application_basis",
            field=models.CharField(
                choices=[("actual_fees", "Actual Fees"), ("final_fees", "Final Fees")],
                default="actual_fees",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="discount_application_basis",
            field=models.CharField(
                choices=[("actual_fees", "Actual Fees"), ("final_fees", "Final Fees")],
                default="actual_fees",
                max_length=20,
            ),
        ),
    ]
