# Generated by Django 4.2.13 on 2026-09-22

from django.core.validators import FileExtensionValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0104_discount_application_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('image_file', models.BinaryField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='crm.paymentinstallment')),
            ],
            options={
                'db_table': 'payment_proofs',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
